<?php

class LoremIpsum
{

    public static function getText(int $length)
    {
        $text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis urna cursus eget nunc scelerisque viverra mauris. Cursus eget nunc scelerisque viverra mauris. Sit amet mattis vulputate enim nulla aliquet. Dictumst quisque sagittis purus sit amet volutpat consequat. Iaculis urna id volutpat lacus laoreet non. Eget nulla facilisi etiam dignissim. Facilisis volutpat est velit egestas dui id ornare. In ornare quam viverra orci sagittis eu volutpat odio. Commodo quis imperdiet massa tincidunt nunc. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Urna nec tincidunt praesent semper feugiat nibh. Hac habitasse platea dictumst quisque sagittis. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Duis at consectetur lorem donec massa sapien.
Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Eu turpis egestas pretium aenean pharetra magna. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. In pellentesque massa placerat duis ultricies lacus sed turpis. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Blandit libero volutpat sed cras ornare arcu dui vivamus. Dictum sit amet justo donec enim diam vulputate ut. Nisi scelerisque eu ultrices vitae auctor. Sit amet est placerat in egestas erat imperdiet. Volutpat diam ut venenatis tellus in. Turpis massa sed elementum tempus egestas sed. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Hac habitasse platea dictumst quisque sagittis purus. Arcu cursus vitae congue mauris. Eget mauris pharetra et ultrices neque ornare. Quam quisque id diam vel quam elementum. Diam sit amet nisl suscipit adipiscing bibendum. Tristique senectus et netus et malesuada fames ac turpis egestas.
Enim sit amet venenatis urna. Quis hendrerit dolor magna eget est lorem ipsum dolor. Pellentesque habitant morbi tristique senectus et netus et. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Ultrices eros in cursus turpis massa tincidunt. Pharetra sit amet aliquam id diam maecenas ultricies mi. Rutrum quisque non tellus orci ac auctor augue mauris augue. Nibh sed pulvinar proin gravida. Proin nibh nisl condimentum id venenatis a condimentum. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Dignissim diam quis enim lobortis scelerisque fermentum dui. Volutpat consequat mauris nunc congue nisi. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Orci phasellus egestas tellus rutrum tellus. Mauris pellentesque pulvinar pellentesque habitant. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper.
Vitae auctor eu augue ut lectus arcu bibendum. Vitae tempus quam pellentesque nec. Risus viverra adipiscing at in tellus. Accumsan in nisl nisi scelerisque eu ultrices. Amet nulla facilisi morbi tempus iaculis urna. Egestas fringilla phasellus faucibus scelerisque. Sit amet tellus cras adipiscing enim eu turpis. Sem et tortor consequat id. Magnis dis parturient montes nascetur ridiculus. Non blandit massa enim nec dui nunc.
Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Ut aliquam purus sit amet luctus venenatis. Eget mauris pharetra et ultrices neque ornare. Consectetur adipiscing elit duis tristique sollicitudin. Ut lectus arcu bibendum at varius vel. Convallis posuere morbi leo urna molestie. Cursus metus aliquam eleifend mi in nulla posuere. Commodo elit at imperdiet dui accumsan. Vel risus commodo viverra maecenas accumsan. Egestas congue quisque egestas diam in. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Scelerisque felis imperdiet proin fermentum leo.
Commodo elit at imperdiet dui accumsan sit. Vulputate ut pharetra sit amet aliquam. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Adipiscing tristique risus nec feugiat in fermentum. Ac turpis egestas maecenas pharetra convallis. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Risus nec feugiat in fermentum posuere urna nec tincidunt. Odio eu feugiat pretium nibh ipsum. Felis eget nunc lobortis mattis aliquam faucibus. Magna ac placerat vestibulum lectus mauris ultrices. Cras ornare arcu dui vivamus arcu felis bibendum.
Id neque aliquam vestibulum morbi blandit cursus risus at. Nulla porttitor massa id neque aliquam vestibulum morbi. Molestie nunc non blandit massa enim nec dui. Lorem sed risus ultricies tristique. Id ornare arcu odio ut sem nulla pharetra diam sit. Rhoncus urna neque viverra justo nec ultrices dui sapien. Purus gravida quis blandit turpis cursus in hac. Morbi tincidunt ornare massa eget. Maecenas sed enim ut sem viverra aliquet. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Eu facilisis sed odio morbi quis commodo odio aenean. Tellus elementum sagittis vitae et leo duis ut diam.
Sed faucibus turpis in eu mi bibendum neque egestas congue. Commodo odio aenean sed adipiscing diam donec adipiscing. Tellus at urna condimentum mattis pellentesque id nibh tortor. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Sed viverra tellus in hac habitasse. Urna porttitor rhoncus dolor purus non enim. Sed augue lacus viverra vitae congue. In ornare quam viverra orci sagittis eu volutpat odio. Tortor vitae purus faucibus ornare suspendisse. Adipiscing diam donec adipiscing tristique risus nec feugiat. Penatibus et magnis dis parturient. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Amet cursus sit amet dictum. Sed cras ornare arcu dui vivamus arcu felis bibendum. Ullamcorper malesuada proin libero nunc. Arcu non odio euismod lacinia. Elementum curabitur vitae nunc sed velit. Facilisis leo vel fringilla est. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Maecenas volutpat blandit aliquam etiam erat velit scelerisque.
Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Porttitor leo a diam sollicitudin tempor id eu nisl. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Facilisis volutpat est velit egestas dui id ornare arcu odio. Commodo sed egestas egestas fringilla phasellus. Ut eu sem integer vitae justo eget magna fermentum iaculis. Sociis natoque penatibus et magnis dis parturient montes. Imperdiet dui accumsan sit amet nulla. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Urna id volutpat lacus laoreet non curabitur gravida arcu. Est sit amet facilisis magna.
Orci porta non pulvinar neque laoreet suspendisse. Augue neque gravida in fermentum et sollicitudin ac orci. Nibh praesent tristique magna sit amet purus gravida quis blandit. Bibendum ut tristique et egestas quis. Pretium aenean pharetra magna ac. Curabitur gravida arcu ac tortor dignissim. Id donec ultrices tincidunt arcu. Ullamcorper morbi tincidunt ornare massa. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Rhoncus dolor purus non enim praesent. Nulla pharetra diam sit amet nisl suscipit. Cursus in hac habitasse platea dictumst. Velit egestas dui id ornare arcu odio ut sem nulla. Ut placerat orci nulla pellentesque dignissim enim sit amet. Venenatis cras sed felis eget velit aliquet sagittis id. Ipsum consequat nisl vel pretium lectus quam id leo. Suscipit adipiscing bibendum est ultricies integer quis. Neque convallis a cras semper auctor neque vitae. Lorem donec massa sapien faucibus et molestie ac feugiat sed.";

        return substr($text, 0, $length);
    }
}